#include QMK_KEYBOARD_H


#include "quantum.h"


#define _BASE 0
#define _NUMBER 1
#define _MOVE 2

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [_BASE] = LAYOUT_5x6_2(KC_NO, KC_TILD, KC_CIRC, KC_LCBR, KC_LBRC, KC_LPRN, KC_RPRN, KC_RBRC, KC_RCBR, KC_DLR, KC_SLSH, KC_NO, KC_BSLS, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_SLSH, TO(2), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_MINS, TO(1), KC_LBRC, KC_NO, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_SCLN, KC_GRV, KC_RBRC, KC_NO, KC_END, KC_NO, KC_NO, KC_COMM, KC_DOT, KC_DEL, KC_HOME, KC_TAB, KC_SPC, KC_ENT, KC_BSPC, KC_LSFT, KC_NO, KC_DEL, KC_RSFT, KC_LGUI, KC_LCTL, KC_LALT, KC_NO),

    [_NUMBER] = LAYOUT_5x6_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LPRN, KC_LBRC, KC_LCBR, KC_RCBR, KC_RBRC, KC_RPRN, KC_NO, KC_NO, KC_NO, TO(0), KC_0, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, TO(2), KC_NO, KC_NO, KC_MINS, KC_SLSH, KC_CIRC, KC_NO, KC_NO, KC_DLR, KC_ASTR, KC_PLUS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),

    [_MOVE] = LAYOUT_5x6_2(KC_NO, KC_NO, KC_ACL0, KC_ACL1, KC_ACL2, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN1, KC_MS_U, KC_WH_U, KC_NO, KC_NO, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_NO, TO(1), KC_NO, KC_MS_L, KC_BTN3, KC_MS_R, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, TO(0), KC_NO, KC_NO, KC_BTN2, KC_MS_D, KC_WH_D, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)

};


#include "oled.c"
