#include QMK_KEYBOARD_H

#include "quantum.h"

#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3
#define _LAYER4 4
#define _LAYER5 5
#define _LAYER6 6
#define _LAYER7 7
#define _LAYER8 8

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
    LAYER3,
    LAYER4,
    LAYER5,
    LAYER6,
    LAYER7,
    LAYER8,
};

// Tap Dance declarations
enum {
    TD_LSFT_CAPS,
    TD_L_RB_SB_B,
    TD_R_RB_SB_B,
};

// Tap Dance definitions
qk_tap_dance_action_t tap_dance_actions[] = {
    // Tap once for Escape, twice for Caps Lock
    [TD_LSFT_CAPS] = ACTION_TAP_DANCE_DOUBLE(KC_LSFT, KC_CAPS),
    [TD_L_RB_SB_B] = ACTION_TAP_DANCE_DOUBLE(KC_LPRN, KC_LBRC),
    [TD_R_RB_SB_B] = ACTION_TAP_DANCE_DOUBLE(KC_RPRN, KC_RBRC),
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

 [_LAYER0] = LAYOUT_5x6_2(
 TG(1), KC_1, KC_2, KC_3, KC_4, KC_5,                               KC_6, KC_7, KC_8, KC_9, KC_0, TG(8),
 KC_BSLS, KC_QUOT, KC_W, KC_E, KC_R, KC_T,                          KC_Y, KC_U, KC_I, KC_O, KC_SCLN, KC_SLSH,
 TO(6), KC_Q, KC_A, KC_S, KC_D, KC_F,                               KC_G, KC_H, KC_J, KC_K, KC_L, TO(7),
  KC_NO, TD(TD_L_RB_SB_B), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_P, TD(TD_R_RB_SB_B), KC_GRV, KC_NO, KC_LCTL, KC_MINS, KC_EQL, KC_COMM, KC_DOT, KC_RALT, KC_NO, TD(TD_LSFT_CAPS), KC_SPC, KC_ENT, KC_BSPC, KC_TAB, KC_ESC, TD(TD_LSFT_CAPS), KC_DEL, KC_LGUI, KC_LALT, KC_RCTL, KC_INS),

 [_LAYER1] = LAYOUT_5x6_2(
 TG(2), KC_7, KC_5, KC_3, KC_1, KC_9,            KC_0, KC_2, KC_4, KC_6, KC_8, TG(0),
 KC_NO, KC_SCLN, KC_COMM, KC_DOT, KC_P, KC_Y,    KC_F, KC_G, KC_C, KC_R, KC_L, KC_NO,
 KC_TRNS, KC_A, KC_O, KC_E, KC_U, KC_I, KC_D,    KC_H, KC_T, KC_N, KC_S, KC_TRNS, KC_NO, KC_NO, KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, KC_Z, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

 [_LAYER2] = LAYOUT_5x6_2(
 TG(8), KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, TG(1), KC_NO, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_NO, KC_TRNS, KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, KC_TRNS, KC_NO, KC_Z, KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

 [_LAYER6] = LAYOUT_5x6_2(
 KC_NO, KC_NO, KC_NO, KC_BTN2, KC_NO, KC_NO,            KC_NO, KC_INS, KC_PSCR, KC_SCRL, KC_PAUS, KC_NO,
 KC_NO, KC_MUTE, KC_BTN1, KC_MS_U, KC_BTN3, KC_WH_U,    KC_PGUP, KC_NO, TO(0), KC_NO, KC_NO, KC_NO,
 TO(0), KC_VOLU, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_D,    KC_PGDN, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, TO(7),
 KC_NO, KC_VOLD, KC_MPRV, KC_MSTP, KC_MPLY, KC_MNXT, KC_NO, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

 [_LAYER7] = LAYOUT_5x6_2(
 KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,              KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_NO,
 KC_NO, KC_PLUS, KC_MINS, KC_LPRN, KC_LBRC, KC_LCBR,    KC_RCBR, KC_RBRC, KC_RPRN, KC_ASTR, KC_SLSH, KC_NO,
 TO(6), KC_P0, KC_P1, KC_P2, KC_P3, KC_P4,              KC_P5, KC_P6, KC_P7, KC_P8, KC_P9, TO(0),
 KC_NO, KC_NO, KC_NO, KC_F11, KC_CIRC, KC_NO, KC_NO, KC_DLR, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

 [_LAYER8] = LAYOUT_5x6_2(
 TG(0), KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TG(2),
  KC_NO, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LALT, KC_6, KC_7, KC_NO, KC_NO, KC_NO, KC_NO, KC_8, KC_SPC, KC_NO, KC_NO, KC_9, KC_0, KC_NO, KC_NO, KC_LGUI, KC_ESC, KC_NO, KC_NO)

};

#include "oled.c"
