# This file intentionally left blank
OLED_DRIVER = SSD1306
SPLIT_KEYBOARD = yes
OLED_ENABLE = yes
LTO_ENABLE = yes
TAP_DANCE_ENABLE = yes
WPM_ENABLE = yes

BOOTMAGIC_ENABLE=no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
FAUXCLICKY_ENABLE = no
HD44780_ENABLE = no
